import type { Metadata } from "next";
import Image from "next/image";
import { headers } from "next/headers";
import { requireTenant } from "@/lib/tenant";
import { getPublicContactSettings, getPublishedPageContent, hasPublishedPrivacy } from "@/lib/public-data";
import { CONTACT_SUBJECTS } from "@/lib/contact";
import { getTurnstileConfiguration } from "@/lib/turnstile";
import { ContactForm, InnerHero } from "../_components";
import { buildPublicMetadata } from "../metadata";
import { formatLocalTelephone, telephoneHref } from "@/lib/public-links";
import { MotionReveal } from "@/components/motion-reveal";

export async function generateMetadata(): Promise<Metadata> { return buildPublicMetadata((await headers()).get("host") ?? "", "/contact", "Contact SWCU | Service Worker Credit Union", "Contact Service Worker Credit Union by phone, email or through the website."); }

export default async function ContactPage() {
  const tenant = await requireTenant((await headers()).get("host") ?? "");
  const [contact, privacyOpen, pages, turnstile] = await Promise.all([getPublicContactSettings(tenant), hasPublishedPrivacy(tenant), getPublishedPageContent(tenant, ["CONTACT_INTRO"]), getTurnstileConfiguration()]);
  return <><InnerHero title="Contact SWCU" summary={pages[0]?.body?.split(/\n/)[0]}/><div className="site-container section-shell"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><MotionReveal className="h-fit"><div>{contact ? <div className="rounded-2xl bg-deep-navy p-7 text-white"><h2 className="font-heading text-2xl font-bold">{contact.organisationName}</h2><div className="mt-6 grid gap-4 text-white/80"><p>{contact.streetAddress}<br/>{contact.postalAddress}</p><div className="overflow-hidden rounded-xl border border-white/15">{contact.contactMapMediaAsset ? <Image src={`/api/media/${contact.contactMapMediaAsset.id}`} alt="Map showing the SWCU office at 300 Waimanu Road, Suva" width={1200} height={650} className="h-auto w-full" /> : <div className="relative flex min-h-52 items-center justify-center overflow-hidden bg-gradient-to-br from-swcu-blue via-ocean-teal to-deep-navy p-8 text-center"><div className="absolute inset-5 rounded-full border border-white/20"/><div className="absolute inset-x-10 top-10 border-t border-dashed border-white/30"/><div className="relative"><p className="font-heading text-lg font-bold text-white">SWCU office</p><p className="mt-2 text-sm text-white/85">{contact.streetAddress}, Fiji</p></div></div>}</div><div className="grid gap-2"><a href={telephoneHref(contact.telephone)} className="font-semibold text-white">Digicel: {formatLocalTelephone(contact.telephone)}</a>{contact.secondaryTelephone && <a href={telephoneHref(contact.secondaryTelephone)} className="font-semibold text-white">Vodafone: {formatLocalTelephone(contact.secondaryTelephone)}</a>}</div><a href={`mailto:${contact.publicEmail}`} className="break-all">{contact.publicEmail}</a>{contact.officeHours && <div><p className="font-semibold text-white">Office hours</p><p className="mt-1 whitespace-pre-line">{contact.officeHours}</p></div>}</div></div> : <p className="rounded-xl border border-dashed p-6">Contact details will appear here when available.</p>}</div></MotionReveal><MotionReveal className="h-fit" index={1}><div>{privacyOpen ? turnstile ? <ContactForm subjects={CONTACT_SUBJECTS} siteKey={turnstile.siteKey}/> : <div className="rounded-2xl bg-soft-blue-grey p-7"><h2 className="font-heading text-2xl font-bold text-deep-navy">Send us an enquiry</h2><p className="mt-4 text-charcoal/75">Online enquiries are temporarily unavailable. Please contact SWCU using the details shown on this page.</p></div> : <div className="rounded-2xl bg-soft-blue-grey p-7"><h2 className="font-heading text-2xl font-bold text-deep-navy">Send us an enquiry</h2><p className="mt-4 text-charcoal/75">The contact form is temporarily unavailable. Please use the contact details on this page to reach SWCU.</p></div>}</div></MotionReveal></div></div></>;
}