/* eslint-disable @next/next/no-img-element -- protected CMS media uses the tenant-aware media route */
import Link from "next/link";
import { headers } from "next/headers";
import { requireTenant } from "@/lib/tenant";
import { requireStaffMembership } from "@/lib/authorise";
import { db } from "@/lib/db";
import { saveLeadershipAction, updateLeadershipAction } from "../actions";
import { AdminActionForm, AdminSubmitButton } from "@/components/admin-action-form";
import { AdminFileSelector } from "@/components/admin-media-upload";

export default async function LeadershipPage() {
  const tenant = await requireTenant((await headers()).get("host") ?? "");
  await requireStaffMembership(tenant, ["ADMINISTRATOR"]);
  const people = await db.leadershipRecord.findMany({ where: { tenantId: tenant.id }, orderBy: [{ group: "asc" }, { sortOrder: "asc" }] });
  return <main className="site-container py-12">
    <Link href="/admin">← Dashboard</Link>
    <h1 className="mt-8 font-heading text-4xl font-bold text-deep-navy">Leadership & Committees</h1>
    <p className="mt-2 text-charcoal/70">Add only approved names and profiles. Records remain unpublished until reviewed.</p>
    <AdminActionForm action={saveLeadershipAction} className="mt-8 grid max-w-3xl gap-3 rounded-card bg-white p-6 sm:grid-cols-2" successMessage="Leadership record saved.">
      <label className="text-sm font-semibold">Name<input name="name" className="mt-1 w-full rounded border p-2" required /></label><label className="text-sm font-semibold">Role / Title<input name="title" className="mt-1 w-full rounded border p-2" required /></label><label className="text-sm font-semibold">Committee<select name="group" defaultValue="Board" className="mt-1 w-full rounded border p-2"><option>Board</option><option>Credit Committee</option><option>Supervisory Committee</option></select></label><label className="text-sm font-semibold sm:col-span-2">Profile / Short Biography<textarea name="profile" className="mt-1 w-full rounded border p-2" rows={3} /></label><label className="text-sm font-semibold">Display Order<input name="sortOrder" type="number" defaultValue="0" className="mt-1 w-full rounded border p-2" /></label><AdminFileSelector name="photo" label="Photo (optional)" accept="image/jpeg,image/png,image/webp" imagePreview />
      <AdminSubmitButton pendingLabel="Saving…" className="rounded bg-swcu-blue px-4 py-2 font-semibold text-white">Save unpublished record</AdminSubmitButton>
    </AdminActionForm>
    <ul className="mt-8 space-y-4">{people.map((person) => <li key={person.id} className="rounded-card bg-white p-5 shadow-card"><AdminActionForm action={updateLeadershipAction} className="grid gap-3 sm:grid-cols-2" successMessage="Leadership record updated."><input type="hidden" name="id" value={person.id}/><label className="text-sm font-semibold">Name<input name="name" defaultValue={person.name} className="mt-1 w-full rounded border p-2" required /></label><label className="text-sm font-semibold">Role / Title<input name="title" defaultValue={person.title} className="mt-1 w-full rounded border p-2" required /></label><label className="text-sm font-semibold">Committee<select name="group" defaultValue={person.group} className="mt-1 w-full rounded border p-2">{!["Board", "Credit Committee", "Supervisory Committee"].includes(person.group) && <option value={person.group}>{person.group}</option>}<option>Board</option><option>Credit Committee</option><option>Supervisory Committee</option></select></label><label className="text-sm font-semibold sm:col-span-2">Profile / Short Biography<textarea name="profile" defaultValue={person.profile ?? ""} className="mt-1 w-full rounded border p-2" rows={3} /></label><label className="text-sm font-semibold">Display Order<input name="sortOrder" type="number" defaultValue={person.sortOrder} className="mt-1 w-full rounded border p-2" /></label><div>{person.mediaAssetId && <div className="mb-3"><p className="mb-2 text-sm font-semibold text-deep-navy">Current photo</p><img src={`/api/media/${person.mediaAssetId}`} alt="" className="h-24 w-24 rounded-xl object-cover" /></div>}<AdminFileSelector name="photo" label={person.mediaAssetId ? "Replace photo (optional)" : "Photo (optional)"} accept="image/jpeg,image/png,image/webp" imagePreview /></div>{person.mediaAssetId && <label className="text-sm"><input name="removePhoto" type="checkbox" /> Remove current photo</label>}<label className="text-sm"><input name="isEnabled" type="checkbox" defaultChecked={person.isEnabled}/> Enabled</label><label className="text-sm"><input name="isPublished" type="checkbox" defaultChecked={person.isPublished}/> Public release approved</label><AdminSubmitButton pendingLabel="Updating…" className="rounded bg-swcu-blue px-3 py-2 font-semibold text-white">Update record</AdminSubmitButton></AdminActionForm></li>)}</ul>
  </main>;
}