import { headers } from "next/headers";
import Link from "next/link";
import { db } from "@/lib/db";
import { requireStaffMembership } from "@/lib/authorise";
import { requireTenant } from "@/lib/tenant";
import { replaceFormDocument, saveFormDocument, uploadFormDocument, removeFormDocument, setFormPublicApproval } from "../actions";
import { AdminWorkflowNotice } from "@/components/admin-workflow-notice";
import { AdminActionForm, AdminSubmitButton } from "@/components/admin-action-form";
import { AdminFileSelector, ConfirmSubmitButton } from "@/components/admin-media-upload";

export default async function FormsAdminPage() {
  const tenant = await requireTenant((await headers()).get("host") ?? "");
  const { membership } = await requireStaffMembership(tenant);
  const editor = membership.role === "EDITOR";
  const forms = await db.formDocument.findMany({ where: { tenantId: tenant.id }, orderBy: { sortOrder: "asc" } });
  const drafts = await db.cmsDraft.findMany({ where: { tenantId: tenant.id, kind: "FORM_DOCUMENT", status: { in: ["DRAFT", "RETURNED_FOR_CHANGES"] } }, select: { targetId: true, revision: true } });
  const revisionFor = (id?: string) => drafts.find((draft) => draft.targetId === id)?.revision ?? "";
  return <main className="min-h-screen bg-soft-blue-grey"><div className="site-container py-12">
    <Link href="/admin" className="text-sm font-semibold text-swcu-blue">← Dashboard</Link>
    <h1 className="mt-8 font-heading text-4xl font-bold text-deep-navy">Forms &amp; Documents</h1>
    <p className="mt-2 text-sm text-charcoal/65">Only enabled documents with an uploaded PDF and deliberate public approval show a public download.</p><AdminWorkflowNotice editor={editor} />
     <AdminActionForm action={uploadFormDocument} className="mt-8 grid max-w-3xl gap-3 rounded-card bg-white p-6 shadow-card sm:grid-cols-2" successMessage="Form saved successfully.">
       <label className="text-sm font-semibold">Form name<input name="title" placeholder="For example, Membership application" required className="mt-1 w-full rounded border p-2" /></label><AdminFileSelector label="PDF document" accept="application/pdf,.pdf" required /><textarea name="description" placeholder="Short description for members" className="rounded border p-2" /><label className="text-sm font-semibold">Document category<input name="category" placeholder="For example, Membership" required className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-semibold">Display order<input name="sortOrder" type="number" defaultValue="0" className="mt-1 w-full rounded border p-2" /></label><label className="text-sm"><input name="isAnnualReport" type="checkbox" /> Annual report</label><label className="text-sm"><input name="isEnabled" type="checkbox" defaultChecked /> Available on website</label><AdminSubmitButton pendingLabel="Uploading…" className="w-fit rounded bg-swcu-blue px-4 py-2 font-semibold text-white">{editor ? "Save Draft" : "Save form"}</AdminSubmitButton>
     </AdminActionForm>
    <ul className="mt-8 max-w-3xl space-y-3">{forms.map((form) => <li key={form.id} className="rounded border bg-white p-4">
        <AdminActionForm action={saveFormDocument} className="grid gap-2 sm:grid-cols-2" successMessage="Form changes saved."><input type="hidden" name="id" value={form.id} /><input type="hidden" name="revision" value={revisionFor(form.id)} /><label className="text-sm font-semibold">Form name<input name="title" defaultValue={form.title} required className="mt-1 w-full rounded border p-2" /></label><textarea name="description" defaultValue={form.description ?? ""} placeholder="Short description" className="rounded border p-2" /><label className="text-sm font-semibold">Document category<input name="category" defaultValue={form.category ?? ""} required className="mt-1 w-full rounded border p-2" /></label><label className="text-sm font-semibold">Display order<input name="sortOrder" type="number" defaultValue={form.sortOrder} className="mt-1 w-full rounded border p-2" /></label><label className="text-sm"><input name="isAnnualReport" type="checkbox" defaultChecked={form.isAnnualReport} /> Annual report</label><label className="text-sm"><input name="isEnabled" type="checkbox" defaultChecked={form.isEnabled} /> Available on website</label><AdminSubmitButton pendingLabel="Saving…" className="w-fit text-sm font-semibold text-swcu-blue">{editor ? "Save Draft" : "Save changes"}</AdminSubmitButton></AdminActionForm>
       <div className="mt-3 flex flex-wrap gap-3 text-sm text-charcoal/60"><span>{form.category} · {form.isAnnualReport ? "Annual report" : "Ordinary form"} · {form.publicApprovedAt ? "Public approved" : "Not public approved"}</span>{!editor && <><AdminActionForm action={setFormPublicApproval} className="contents" successMessage={form.publicApprovedAt ? "Public release revoked." : "Public release approved."}><input type="hidden" name="id" value={form.id}/><input type="hidden" name="approved" value={form.publicApprovedAt ? "false" : "true"}/>{form.publicApprovedAt ? <ConfirmSubmitButton label="Revoke public release" message="Revoke this form's public release?" className="font-semibold text-swcu-blue"/> : <AdminSubmitButton pendingLabel="Approving…" className="font-semibold text-swcu-blue">Approve public release</AdminSubmitButton>}</AdminActionForm><AdminActionForm action={removeFormDocument} className="contents" successMessage="Form removed."><input type="hidden" name="id" value={form.id}/><ConfirmSubmitButton label="Remove" message="Remove this form and its public download?" className="font-semibold text-swcu-red"/></AdminActionForm></>}</div>
        <div className="mt-3"><AdminActionForm action={replaceFormDocument} className="flex flex-wrap items-end gap-3" successMessage="PDF replaced successfully."><input type="hidden" name="id" value={form.id}/><input type="hidden" name="revision" value={revisionFor(form.id)}/><AdminFileSelector label="Replace PDF" accept="application/pdf,.pdf" required/><AdminSubmitButton pendingLabel="Replacing…" className="font-semibold text-ocean-teal">{editor ? "Propose replacement" : "Replace PDF"}</AdminSubmitButton></AdminActionForm></div>
    </li>)}</ul>
  </div></main>;
}