import Link from "next/link";
import { headers } from "next/headers";
import { db } from "@/lib/db";
import { requireStaffMembership } from "@/lib/authorise";
import { requireTenant } from "@/lib/tenant";

export default async function ContactEnquiriesPage() {
  const tenant = await requireTenant((await headers()).get("host") ?? "");
  await requireStaffMembership(tenant, ["ADMINISTRATOR"]);
  const enquiries = await db.contactSubmission.findMany({ where: { tenantId: tenant.id }, orderBy: { submittedAt: "desc" }, select: { id: true, reference: true, subject: true, status: true, submittedAt: true } });
  const newCount = enquiries.filter((item) => item.status === "NEW").length;
  const handlingCount = enquiries.filter((item) => item.status === "BEING_HANDLED").length;
  return <main className="min-h-screen bg-soft-blue-grey"><div className="site-container py-12"><Link href="/admin" className="text-sm font-semibold text-swcu-blue">← Dashboard</Link><div className="mt-8 flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Admin work</p><h1 className="mt-2 font-heading text-4xl font-bold text-deep-navy">Contact Enquiries</h1><p className="mt-2 text-charcoal/70">Review and manage messages received through the public Contact form.</p></div><div className="flex gap-3 text-sm"><span className="rounded-full bg-white px-3 py-1 font-semibold text-deep-navy">{newCount} new</span><span className="rounded-full bg-white px-3 py-1 font-semibold text-deep-navy">{handlingCount} being handled</span></div></div><section className="mt-8 overflow-hidden rounded-card border border-deep-navy/10 bg-white shadow-card"><div className="hidden grid-cols-[1fr_1.5fr_1fr_1fr_auto] gap-4 border-b border-deep-navy/10 bg-soft-blue-grey px-5 py-3 text-xs font-bold uppercase tracking-wide text-charcoal/65 md:grid"><span>Reference</span><span>Subject</span><span>Received</span><span>Status</span><span className="sr-only">Action</span></div>{enquiries.length === 0 ? <p className="p-6 text-charcoal/70">No enquiries have been received.</p> : <div className="divide-y divide-deep-navy/10">{enquiries.map((item) => <div key={item.id} className="grid gap-3 px-5 py-4 text-sm md:grid-cols-[1fr_1.5fr_1fr_1fr_auto] md:items-center md:gap-4"><div><span className="block text-xs font-bold uppercase tracking-wide text-charcoal/55 md:hidden">Reference</span><span className="font-semibold text-deep-navy">{item.reference}</span></div><div><span className="block text-xs font-bold uppercase tracking-wide text-charcoal/55 md:hidden">Subject</span><span>{item.subject}</span></div><div><span className="block text-xs font-bold uppercase tracking-wide text-charcoal/55 md:hidden">Received</span><time className="text-charcoal/65">{item.submittedAt.toLocaleString()}</time></div><div><span className="block text-xs font-bold uppercase tracking-wide text-charcoal/55 md:hidden">Status</span><span className="font-semibold">{item.status === "NEW" ? "New" : item.status === "BEING_HANDLED" ? "Being handled" : "Closed"}</span></div><Link prefetch={false} href={`/admin/contact-enquiries/${item.id}`} className="font-semibold text-swcu-blue underline">Open enquiry</Link></div>)}</div>}</section></div></main>;
}