ALTER TABLE "calculator_settings"
  ADD COLUMN IF NOT EXISTS "monthlyInterestRate" DECIMAL(7,4) NOT NULL DEFAULT 1.0000,
  ADD COLUMN IF NOT EXISTS "weeklyEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "fortnightlyEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "monthlyEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "takeHomePayPercentage" DECIMAL(5,2) NOT NULL DEFAULT 50.00,
  ADD COLUMN IF NOT EXISTS "establishmentFeeType" VARCHAR(20) NOT NULL DEFAULT 'NONE',
  ADD COLUMN IF NOT EXISTS "establishmentFeeValue" DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS "establishmentFeeFinanced" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "minimumLoanAmount" DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS "maximumLoanAmount" DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS "minimumRepayments" INTEGER,
  ADD COLUMN IF NOT EXISTS "maximumRepayments" INTEGER;